const PIANO_KEY_HEIGHT = 24;
const PIANO_KEY_WIDTH = 100;
const NOTES = ['C','D','E','F','G','A','B'];
const NOTES2 = ['C#','D#','F#','G#','A#'];
const OCTAVES = 8;
const PIXELS_PER_BEAT = 100;
const PIANO_ROLL_TOTAL_HEIGHT = 12 * OCTAVES + PIANO_KEY_HEIGHT * 12 * OCTAVES;

export {PIANO_ROLL_TOTAL_HEIGHT, PIANO_KEY_WIDTH, PIANO_KEY_HEIGHT, NOTES, NOTES2, OCTAVES, PIXELS_PER_BEAT};